version: '3.1'

services:

  eval-mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306
    volumes:
      - eval-mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  eval-mysql: